process.env.NODE_ENV = 'test';
process.env.TEST_DIALECT = 'postgres';
process.env.DATABASE_URL = 'postgres://aidin@127.0.0.1:55439/janebi_audit';
process.env.JWT_ACCESS_SECRET = 'local-audit-access-secret';
process.env.JWT_REFRESH_SECRET = 'local-audit-refresh-secret';
const { db, closeDb, dbReady } = await import('../../server/db/index.js');
await dbReady();
await db.query.users.findMany({ limit: 1 });
await closeDb();
console.log('PASS: isolated PostgreSQL migrations and real DB initialization');
